// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> Result;
RWStructuredBuffer<float> _verticalProperty;
RWStructuredBuffer<float> _horizontalProperty;

uint2 _simRes;

static const int oneCellResolution = 100;
static const int arrowHalfWidth = 5;
static const int arrowTipLength = 12;
static const float baseArrowLength = 30;
static const float4 arrowColor = float4(0.1, 0.1, 0.6, 0);

void drawArrow(float2 arrowOrigin, int2 direction, int arrowLength)
{
    
    //Result[viewXY] = 1;
    
    
    //find topLeftCorner
    int2 rectangleStart = arrowOrigin - (abs(direction.yx) * arrowHalfWidth);

    int length = direction.x == 0 ? arrowHalfWidth * 2 : arrowLength;
    int height = direction.y == 0 ? arrowHalfWidth * 2 : arrowLength;

    if (direction.x == -1)
    {
        rectangleStart.x = rectangleStart.x - length;
    }
    if (direction.y == -1)
    {
        rectangleStart.y = rectangleStart.y - height;
    }

    for (int i = 0; i < length; i++)
    {
        for (int j = 0; j < height; j++)
        {
            Result[rectangleStart + int2(i, j)] = arrowColor;
        }
    }

    int2 arrowTip = rectangleStart + (int2(length, height) * ((direction + 1) / 2)) + (abs(direction.yx) * arrowHalfWidth) + (direction * arrowTipLength);
    
    for (int i = 0; i < arrowTipLength; i++)
    {
        for (int j = -i; j < i; j++)
        {
            int x = i;
            int y = j;

            if (direction.x == 1 || direction.y == 1)
            {
                x = -i - 1;
            }
            int2 finalXY = direction.y == 0 ? int2(x, y) : int2(y, x);
            
            Result[arrowTip + finalXY] = arrowColor;
        }
    }
    
    return;
}

//called once for each cell
[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    if(id.x > _simRes.x || id.y > _simRes.y){
        return;
    }
    
    uint2 cellXY = id.xy;
    uint cellXY_1D = cellXY.x * _simRes.y + cellXY.y;

    
    //vertical arrow
    int2 direction = int2(0,1); //must be one of (1,0) (-1,0) (0,1) (0,-1)
    uint2 viewXY = (cellXY * oneCellResolution) + int2(oneCellResolution * 0.5, 0);
    
    if (abs(_verticalProperty[cellXY_1D]) >= 0.1)
    {
        
        float arrowLength = _verticalProperty[cellXY_1D] * baseArrowLength;
        if (arrowLength < 0)
        {
            arrowLength = abs(arrowLength);
            direction = direction * -1;
        }
    
        drawArrow(viewXY, direction, arrowLength);
    }
    
    //hprozontal arrow
    direction = int2(1, 0);
    
    viewXY = (cellXY * oneCellResolution) + int2(0, oneCellResolution * 0.5);
    
    
    if (_horizontalProperty[cellXY_1D] >= 0.1 || _horizontalProperty[cellXY_1D] <= -0.1)
    {
        float arrowLength = _horizontalProperty[cellXY_1D] * baseArrowLength;
        if (arrowLength < 0)
        {
            arrowLength = abs(arrowLength);
            direction = direction * -1;
        }
        
        drawArrow(viewXY, direction, arrowLength);
    }
    

}


