// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain
#pragma kernel solveIncompressibility
#pragma kernel extrapolateH
#pragma kernel extrapolateV
#pragma kernel advectVelH
#pragma kernel advectVelV


// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> Result;

float Resolution;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    //TODO: insert actual code here!

    Result[id.xy] = float4(id.x & id.y, (id.x & 15)/15.0, (id.y & 15)/15.0, 0.0);

    float x = id.x / Resolution;
    float y = id.y / Resolution;

    Result[id.xy] = float4(x, y, 1.0, 0.0);

    if(id.x == Resolution / 2 || id.y == Resolution / 2 ||
        id.x + 1 == Resolution / 2 || id.y + 1== Resolution / 2 ||
        id.x - 1 == Resolution / 2 || id.y - 1== Resolution / 2
        
        )
        Result[id.xy] = float4(1, 1, 1, 0.0);
}



RWStructuredBuffer<float> _pressure;
RWStructuredBuffer<int>   _type;        // 0 - wall  | 1 - fluid
RWStructuredBuffer<float> _velocityV;
RWStructuredBuffer<float> _velocityH;
RWTexture2D<float4> _color;


int resolutionWidth;
int resolutionHeight;



int getCoordPressure(int x, int y, bool simulationSpace) {
    if(simulationSpace){
        x++; y++;
    }
    return x * resolutionWidth + y;
}
int getType(int x, int y){
    if(x < 0 || y < 0 || x > resolutionHeight || y > resolutionWidth)
        return 0;
    x++; y++;
    return _type[x * resolutionWidth + y];
}
int getCoordH_Left(int x, int y, bool simulationSpace) {
    if(simulationSpace){
        x++; y++;
    }
    return x * resolutionWidth + y + x; // + x; is to account for the last edge of a row
}
int getCoordH_Right(int x, int y, bool simulationSpace) {
    if(simulationSpace){
        x++; y++;
    }
    return x * resolutionWidth + y + 1 + x; // + x; is to account for the last edge of a row
}
int getCoordV_Up(int x, int y, bool simulationSpace) {
    if(simulationSpace){
        x++; y++;
    }
    return x * resolutionWidth + y;
}
int getCoordV_Down(int x, int y, bool simulationSpace) {
    if(simulationSpace){
        x++; y++;
    }
    return x * resolutionWidth + y + 1;
}


[numthreads(8, 8, 1)]
void solveIncompressibility(uint3 id: SV_DispatchThreadID){

    if(_type[id.x] == 0)
        return;

    int type_up     = getType(id.x - 1, id.y); 
    int type_down   = getType(id.x + 1, id.y);
    int type_left   = getType(id.x, id.y - 1);
    int type_right  = getType(id.x, id.y + 1);

    // orthogonally connected cells that are fluid
    int fluidCells = type_up + type_down + type_left + type_right;

    if(fluidCells == 0)
        return;

    //calculate outflow (divergence)
    float div =   _velocityH[getCoordH_Right(id.x, id.y, true)] 
                - _velocityH[getCoordH_Left (id.x, id.y, true)] 
                + _velocityV[getCoordV_Down (id.x, id.y, true)] 
                - _velocityV[getCoordV_Up   (id.x, id.y, true)];

    //divergence average on fluid edges
    float p  = -div / fluidCells;
    p *= 1.9;
    _pressure[getCoordPressure(id.x, id.y, true)] += 1 * p;

    _velocityH[getCoordH_Left (id.x, id.y, true)] -= type_left * p;
    _velocityH[getCoordH_Right(id.x, id.y, true)] -= type_right* p;
    _velocityV[getCoordV_Up   (id.x, id.y, true)] -= type_up * p;
    _velocityV[getCoordV_Down (id.x, id.y, true)] -= type_down * p;




    int cellType = _type[getCoordPressure(id.x, id.y, true)];
    _color[id.xy] = float4(1, 1, 1, 0.0);
    //_color[id.xy] = float4(cellType, cellType, cellType, 0.0);
}



[numthreads(32, 1, 1)]
void extrapolateH(uint3 id: SV_DispatchThreadID){
    _velocityH[getCoordH_Left(id.x, 0, false)] = _velocityH[getCoordH_Right(id.x, 0, false)];

    _velocityH[getCoordH_Right(id.x, resolutionWidth, false)] = _velocityH[getCoordH_Left(id.x, resolutionWidth, false)];
}

[numthreads(32, 1, 1)]
void extrapolateV(uint3 id: SV_DispatchThreadID){
    _velocityV[getCoordV_Up(0, id.x, false)] = _velocityV[getCoordV_Down(0, id.x, false)];

    _velocityV[getCoordV_Down(resolutionHeight, id.x, false)] = _velocityV[getCoordV_Up(resolutionHeight, id.x, false)];
}

/*
//get position of center of an edge; ex: left edge of cell (0,0) will have the center at (0.5, 0)
uint2 getPosVerticalEdges(uint index, bool simulationSpace){
    uint trueResWidth = resolutionWidth + 2;
    uint x = index / (trueResWidth + 1);  // x at which edge starts, have to go down 0.5 to find center
    uint y = index % trueResWidth;

    return uint2(x,y);
}

uint2 getPosHorizontalEdges(uint index){
    uint trueResWidth = resolutionWidth + 2;
    uint x = index / trueResWidth;  // x at which edge starts, have to go down 0.5 to find center
    uint y = index % trueResWidth;

    return uint2(x, y);
}

float avgV(int x, int y){
    _velocityV[getCoordV_Up()]
}*/



RWStructuredBuffer<float> _newH;
RWStructuredBuffer<float> _newV;
float dt;

[numthreads(64, 1, 1)] //Call dispatch with (x / 64, y, 1)
void advectVelH(uint3 id: SV_DispatchThreadID){
    
}

uint sim1D_to_real1D__VeloctyV(uint index) {
    uint trueResWidth = resolutionWidth + 2;
    uint trueIndex = (index / resolutionWidth) + 1; //get row; +1 because first row does not belong to simulation space
    trueIndex = trueIndex * trueResWidth; //set trueIndex to start of row
    trueIndex = trueIndex + (index % resolutionWidth) + 1; //add the collumn necessary plus first one
    return trueIndex;
}

//This function deals only with velocityV coordinates
uint sim2D_to_real1D_VelocityV(uint2 index) {
    uint x = index.x + 1; //+1 is accounting for the border cell
    uint y = index.y + 1;
    return x * resolutionWidth + y;
}

//get the cell to the top of the given edge in real2D 
uint2 sim2D_velocityV_to_real2D_topCell(uint2 index) {
    int x = index.x;
    int y = index.y + 1;
    return uint2(x, y);
}
uint2 sim2D_velocityV_to_real2D_bottomCell(uint2 index) {
    int x = index.x + 1;
    int y = index.y + 1;
    return uint2(x, y);
}

//get the average velocityH in the center of the velocityV edge between the to given cells; 
float avgH(uint2 topCell) {
    float topLeft     = _velocityH[getCoordH_Left (topCell.x, topCell.y, false)];
    float topRight    = _velocityH[getCoordH_Right(topCell.x, topCell.y, false)];
    float bottomLeft  = _velocityH[getCoordH_Left (topCell.x + 1, topCell.y, false)]; 
    float bottomRight = _velocityH[getCoordH_Right(topCell.x + 1, topCell.y, false)];

    float average = (topLeft + topRight + bottomLeft + bottomRight)* 0.25;

    return average;
}

//calculates the weighted average of vertical speed on "pos"
float getVerticalSpeed(float2 pos) {
    uint2 leftCell = uint2((uint) pos.x, (uint) pos.y - 0.5);

    //edge center for top left edge
    float2 tl = float2(leftCell.x, leftCell.y + 0.5); 

    //vector going from "tl" to "pos", gives us the distance between the two points
    float2 vec = pos-tl;

    float dx = vec.x;
    float dy = vec.y;
    float sx = dx - 1;
    float sy = dy - 1;

    float avg = sx * sy * _velocityV[getCoordV_Up(leftCell.x, leftCell.y, false)] + 
                dx * sy * _velocityV[getCoordV_Down(leftCell.x, leftCell.y, false)] + 
                sx * dy * _velocityV[getCoordV_Up(leftCell.x, leftCell.y + 1, false)] + 
                dx * dy * _velocityV[getCoordV_Down(leftCell.x, leftCell.y + 1, false)];

    return avg;
}



[numthreads(64, 1, 1)]
void advectVelV(uint3 id: SV_DispatchThreadID){
    uint  velocityV_real1D = sim2D_to_real1D_VelocityV(id.xy);
    uint2 velocityV_real2D = id.xy + 1;
    uint2 topCell_real2D = sim2D_velocityV_to_real2D_topCell(id.xy);
    uint2 bottomCell_real2D = sim2D_velocityV_to_real2D_bottomCell(id.xy);

    if(getType(topCell_real2D.x, topCell_real2D.y) != 0 &&
       getType(bottomCell_real2D.x, bottomCell_real2D.y) 
      ) {
        float velV = _velocityV[velocityV_real1D];
        float velH = avgH(topCell_real2D);

        //center of velocityV edge
        float2 edgeCenter = float2(bottomCell_real2D.x, bottomCell_real2D.y + 0.5);

        //calculate where the "particle" at the edge center was in the previous iteration
        float2 newPos = float2(edgeCenter.x - (dt * velV), 
                               edgeCenter.y - (dt * velH));

        _newV[velocityV_real1D] = getVerticalSpeed(newPos);
    }
       
}