// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> Result;
RWStructuredBuffer<float> _type;


//uint2 _viewRes;
uint2 _simRes;


[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    if (id.x > _simRes.x || id.y > _simRes.y)
    {
        return;
    }
    
    uint2 simXY = id.xy;
    
    uint simXY_1D = simXY.x * _simRes.y + simXY.y;

    float c = _type[simXY_1D];
    
    Result[id.xy] = float4(c, c, c, 0.0);
}
