// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> Result;
RWStructuredBuffer<float> _property;

uint2 _viewRes;
uint2 _simRes;


[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    if(id.x > _viewRes.x || id.y > _viewRes.y){
        return;
    }
    uint2 viewXY = id.xy;
    uint2 simXY = viewXY * _simRes / _viewRes;

    uint simXY_1D = simXY.x * _simRes.y + simXY.y;

    float c = _property[simXY_1D];

    Result[id.xy] = float4(c, c, c, 0.0);
}
